stages:
  - lint
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

include:
  - project: 'sertit/groupware'
    file: '/ci_templates/arcgis_plugin.yaml'

trigger_sertit_atools:
  extends: .trigger_sertit_atools_update_tool
  variables:
    PROJECT_ROOT: "rusle"

deploy_registry:
  image: python:latest
  stage: deploy
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    # Deploy if tag
    - if: $CI_COMMIT_TAG
      when: on_success
    # Manual deploy if commit to the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
