stages:
  - bot
  - lint
  - test
  - deploy

include:
  - project: 'sertit/groupware'
    file: '/ci_templates/arcgis_plugin.yaml'
  - project: 'sertit/groupware'
    file: '/ci_templates/deploy_gitlab_registry.yaml'
  - project: 'sertit/groupware'
    file: '/ci_templates/build_docker_bake.yaml'

deploy:sertit_atools:
  extends: .trigger_sertit_atools_update_tool
  variables:
    PROJECT_ROOT: "rusle"

deploy:registry:
  extends: .upload_wheel

deploy:docker:
  extends: .deploy_container_bake
  stage: deploy
  variables:
    TARGET: "rusle"
  rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
     when: manual
     variables:
       IMAGE_TAGS: "sertit/arcgispro-eo:rusle_latest,$CI_REGISTRY_IMAGE:latest"
   - if: $CI_COMMIT_TAG
     variables:
       IMAGE_TAGS: "sertit/arcgispro-eo:rusle_stable,$CI_REGISTRY_IMAGE:stable"
  needs:
    - deploy:registry