stages:
  - lint
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

include:
  - project: 'sertit/groupware'
    file: '/ci_templates/arcgis_plugin.yaml'
  - project: 'sertit/groupware'
    file: '/ci_templates/deploy_gitlab_registry.yaml'
  - project: 'sertit/groupware'
    file: '/ci_templates/build_docker_bake.yaml'

deploy:sertit_atools:
  extends: .trigger_sertit_atools_update_tool
  variables:
    PROJECT_ROOT: "rusle"

deploy:registry:
  extends: .upload_wheel

deploy:docker:
  extends: .deploy_container_bake
  stage: deploy
  before_script:
    - docker login -u sertit -p$DOCKER_HUB_TOKEN
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p$CI_REGISTRY_PASSWORD
  variables:
    TARGET: "rusle"
  rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
     when: manual
     variables:
       IMAGE_TAGS: "sertit/arcgispro-eo:rusle_latest,$CI_REGISTRY_IMAGE:stable"
   - if: $CI_COMMIT_BRANCH
     variables:
       IMAGE_TAGS: "sertit/arcgispro-eo:rusle_stable,$CI_REGISTRY_IMAGE:stable"
  needs:
    - deploy:registry